In [85]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [7]:
harris_precincts = pd.read_csv('/Users/data30nana/Downloads/red605_county_vtd_22g_population.csv')

In [9]:
harris_precincts.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Total,Unnamed: 4,Anglo,Non-Anglo,Unnamed: 7,Unnamed: 8,Asian,...,Unnamed: 13,%Anglo,%Non-Anglo,Unnamed: 16,Unnamed: 17,%Asian,%Black,%Hispanic,Unnamed: 21,%B+H
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Anderson,Total:,NaN,"57,922",NaN,"33,098","24,824",NaN,NaN,543,...,NaN,57.1,42.9,NaN,NaN,0.9,21.2,19.2,NaN,39.9
2,NaN,VAP:,NaN,"47,381",NaN,"27,667","19,714",NaN,NaN,396,...,NaN,58.4,41.6,NaN,NaN,0.8,21.4,17.6,NaN,38.8
3,1,Total:,NaN,"3,153",NaN,"1,660","1,493",NaN,NaN,53,...,NaN,52.6,47.4,NaN,NaN,1.7,29.0,15.4,NaN,43.8
4,NaN,VAP:,NaN,"2,340",NaN,"1,347",993,NaN,NaN,40,...,NaN,57.6,42.4,NaN,NaN,1.7,27.0,12.1,NaN,38.9

In [12]:
harris_precincts.drop(['Unnamed: 2'], axis=1, inplace=True)

In [14]:
harris_precincts.drop(['Unnamed: 4', 'Unnamed: 7', 'Unnamed: 13'], axis=1, inplace=True)

In [16]:
harris_precincts.drop(['Unnamed: 8', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 21'], axis=1, inplace=True)

In [19]:
harris_precincts.drop(0, axis=0, inplace=True)

In [28]:
harris_precincts.iloc[8732]

Unnamed: 0       Harris
Unnamed: 1       Total:
Total         4,731,145
Anglo         1,309,593
Non-Anglo     3,421,552
Asian           392,435
Black           981,484
Hisp          2,034,709
B+H           2,967,268
%Anglo             27.7
%Non-Anglo         72.3
%Asian              8.3
%Black             20.7
%Hispanic          43.0
%B+H               62.7
Name: 8733, dtype: object

In [31]:
harris_precincts.truncate(before=8733)

,Unnamed: 0,Unnamed: 1,Total,Anglo,Non-Anglo,Asian,Black,Hisp,B+H,%Anglo,%Non-Anglo,%Asian,%Black,%Hispanic,%B+H
8733,Harris,Total:,"4,731,145","1,309,593","3,421,552","392,435","981,484","2,034,709","2,967,268",27.7,72.3,8.3,20.7,43.0,62.7
8734,NaN,VAP:,"3,519,584","1,075,663","2,443,921","302,348","712,166","1,405,353","2,091,400",30.6,69.4,8.6,20.2,39.9,59.4
8735,1,Total:,"1,979","1,140",839,193,148,454,593,57.6,42.4,9.8,7.5,22.9,30.0
8736,NaN,VAP:,"1,644",959,685,157,118,369,482,58.3,41.7,9.5,7.2,22.4,29.3
8737,2,Total:,"4,770","2,565","2,205",472,399,"1,280","1,635",53.8,46.2,9.9,8.4,26.8,34.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20025,NaN,VAP:,"1,075",149,926,4,9,915,922,13.9,86.1,0.4,0.8,85.1,85.8
20026,001a,Total:,"1,432",87,"1,345",14,21,"1,315","1,325",6.1,93.9,1.0,1.5,91.8,92.5
20027,NaN,VAP:,956,69,887,11,11,870,875,7.2,92.8,1.2,1.2,91.0,91.5
20028,004a,Total:,956,54,902,1,13,890,897,5.6,94.4,0.1,1.4,93.1,93.8
20029,NaN,VAP:,681,46,635,1,5,628,630,6.8,93.2,0.1,0.7,92.2,92.5

In [32]:
harris_precincts = harris_precincts.truncate(before=8733)

In [34]:
harris_precincts.reset_index()

,index,Unnamed: 0,Unnamed: 1,Total,Anglo,Non-Anglo,Asian,Black,Hisp,B+H,%Anglo,%Non-Anglo,%Asian,%Black,%Hispanic,%B+H
0,8733,Harris,Total:,"4,731,145","1,309,593","3,421,552","392,435","981,484","2,034,709","2,967,268",27.7,72.3,8.3,20.7,43.0,62.7
1,8734,NaN,VAP:,"3,519,584","1,075,663","2,443,921","302,348","712,166","1,405,353","2,091,400",30.6,69.4,8.6,20.2,39.9,59.4
2,8735,1,Total:,"1,979","1,140",839,193,148,454,593,57.6,42.4,9.8,7.5,22.9,30.0
3,8736,NaN,VAP:,"1,644",959,685,157,118,369,482,58.3,41.7,9.5,7.2,22.4,29.3
4,8737,2,Total:,"4,770","2,565","2,205",472,399,"1,280","1,635",53.8,46.2,9.9,8.4,26.8,34.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11292,20025,NaN,VAP:,"1,075",149,926,4,9,915,922,13.9,86.1,0.4,0.8,85.1,85.8
11293,20026,001a,Total:,"1,432",87,"1,345",14,21,"1,315","1,325",6.1,93.9,1.0,1.5,91.8,92.5
11294,20027,NaN,VAP:,956,69,887,11,11,870,875,7.2,92.8,1.2,1.2,91.0,91.5
11295,20028,004a,Total:,956,54,902,1,13,890,897,5.6,94.4,0.1,1.4,93.1,93.8
11296,20029,NaN,VAP:,681,46,635,1,5,628,630,6.8,93.2,0.1,0.7,92.2,92.5

In [43]:
harris_precincts = harris_precincts.fillna('')

In [44]:
harris_precincts.iloc[2337]

index            11070
Unnamed: 0    Harrison
Unnamed: 1      Total:
Total           68,839
Anglo           42,039
Non-Anglo       26,800
Asian              718
Black           14,553
Hisp             9,839
B+H             24,107
%Anglo            61.1
%Non-Anglo        38.9
%Asian             1.0
%Black            21.1
%Hispanic         14.3
%B+H              35.0
Name: 2337, dtype: object

In [41]:
harris_precincts = harris_precincts.reset_index()

In [46]:
harris_precincts = harris_precincts.truncate(after=2336)

In [47]:
harris_precincts.drop(['index'], axis=1, inplace=True)

In [49]:
harris_precincts.rename(columns = {'Unnamed: 0':'Precincts', 'Unnamed: 1':'Population'}, inplace = True)

In [60]:
total_precincts = pd.DataFrame(harris_precincts)

In [75]:
target_precincts1 = total_precincts.iloc[18:24]
target_precincts2 = total_precincts.iloc[88:90]
target_precincts3 = total_precincts.iloc[94:96]
target_precincts4 = total_precincts.iloc[572:574]
target_precincts5 = total_precincts.iloc[696:698]
target_precincts6 = total_precincts.iloc[760:762]
target_precincts7 = total_precincts.iloc[824:826]
target_precincts8 = total_precincts.iloc[862:866]
target_precincts9 = total_precincts.iloc[1332:1334]
target_precincts10 = total_precincts.iloc[1508:1510]
target_precincts11 = total_precincts.iloc[1588:1592]

In [76]:
target_precincts = pd.concat([target_precincts1, target_precincts2, target_precincts3, target_precincts4, target_precincts5, target_precincts6, target_precincts7, target_precincts8, target_precincts9, target_precincts10, target_precincts11], axis=0)

In [77]:
target_precincts

,Precincts,Population,Total,Anglo,Non-Anglo,Asian,Black,Hisp,B+H,%Anglo,%Non-Anglo,%Asian,%Black,%Hispanic,%B+H
18,9,Total:,"4,044",931,"3,113",201,"1,261","1,640","2,856",23.0,77.0,5.0,31.2,40.6,70.6
19,,VAP:,"3,280",872,"2,408",171,890,"1,312","2,177",26.6,73.4,5.2,27.1,40.0,66.4
20,10,Total:,"3,587",385,"3,202",68,143,"2,991","3,115",10.7,89.3,1.9,4.0,83.4,86.8
21,,VAP:,"2,902",332,"2,570",55,127,"2,379","2,497",11.4,88.6,1.9,4.4,82.0,86.0
22,11,Total:,"3,492",295,"3,197",62,194,"2,962","3,133",8.4,91.6,1.8,5.6,84.8,89.7
23,,VAP:,"2,784",275,"2,509",49,173,"2,294","2,450",9.9,90.1,1.8,6.2,82.4,88.0
88,44,Total:,"3,799",564,"3,235",70,229,"2,924","3,140",14.8,85.2,1.8,6.0,77.0,82.7
89,,VAP:,"2,980",472,"2,508",50,187,"2,253","2,432",15.8,84.2,1.7,6.3,75.6,81.6
94,46,Total:,"5,033",471,"4,562",76,949,"3,531","4,453",9.4,90.6,1.5,18.9,70.2,88.5
95,,VAP:,"3,810",425,"3,385",62,542,"2,767","3,301",11.2,88.8,1.6,14.2,72.6,86.6
572,285,Total:,"5,334",148,"5,186",38,"1,979","3,188","5,126",2.8,97.2,0.7,37.1,59.8,96.1
573,,VAP:,"3,985",121,"3,864",28,"1,627","2,215","3,818",3.0,97.0,0.7,40.8,55.6,95.8
696,347,Total:,"8,019","2,017","6,002",343,260,"5,362","5,565",25.2,74.8,4.3,3.2,66.9,69.4
697,,VAP:,"5,783","1,721","4,062",262,183,"3,571","3,726",29.8,70.2,4.5,3.2,61.7,64.4
760,379,Total:,"3,190",82,"3,108",19,"1,395","1,726","3,081",2.6,97.4,0.6,43.7,54.1,96.6
761,,VAP:,"2,458",78,"2,380",16,"1,182","1,206","2,354",3.2,96.8,0.7,48.1,49.1,95.8
824,411,Total:,"6,917",494,"6,423",82,405,"5,962","6,323",7.1,92.9,1.2,5.9,86.2,91.4
825,,VAP:,"4,796",427,"4,369",51,320,"4,006","4,302",8.9,91.1,1.1,6.7,83.5,89.7
862,430,Total:,"8,039",724,"7,315","1,989","1,403","3,994","5,281",9.0,91.0,24.7,17.5,49.7,65.7
863,,VAP:,"5,556",560,"4,996","1,216",949,"2,876","3,748",10.1,89.9,21.9,17.1,51.8,67.5
864,431,Total:,"22,307","1,213","21,094","1,930","4,456","14,800","18,990",5.4,94.6,8.7,20.0,66.3,85.1
865,,VAP:,"15,519",975,"14,544","1,309","3,207","10,085","13,116",6.3,93.7,8.4,20.7,65.0,84.5
1332,665,Total:,"4,408","2,556","1,852",90,124,"1,509","1,620",58.0,42.0,2.0,2.8,34.2,36.8
1333,,VAP:,"3,260","2,015","1,245",57,81,994,"1,065",61.8,38.2,1.7,2.5,30.5,32.7
1508,752,Total:,"3,252","1,109","2,143",100,217,"1,825","2,005",34.1,65.9,3.1,6.7,56.1,61.7
1509,,VAP:,"2,440",946,"1,494",83,150,"1,251","1,377",38.8,61.2,3.4,6.1,51.3,56.4
1588,792,Total:,"3,947",194,"3,753",44,565,"3,165","3,696",4.9,95.1,1.1,14.3,80.2,93.6
1589,,VAP:,"2,881",162,"2,719",37,455,"2,229","2,669",5.6,94.4,1.3,15.8,77.4,92.6
1590,793,Total:,"8,417","1,467","6,950",158,727,"6,051","6,685",17.4,82.6,1.9,8.6,71.9,79.4
1591,,VAP:,"5,923","1,307","4,616",108,432,"4,040","4,419",22.1,77.9,1.8,7.3,68.2,74.6

In [ ]:
# All Target Precincts, excluding one, are at most 40% White/Anglo. Excluding one, all have Asian %s between 0 and 5.5%.

In [ ]:
# % Black is rather variable, so it will not be used for identifying comparable precincts. % Hispanic is at least 30%.

In [ ]:
# % Black and Hispanic is at least 60%, excluding one or two precincts.

In [90]:
print(harris_precincts.dtypes)
harris_precincts['%Non-Anglo'] = pd.to_numeric(harris_precincts['%Non-Anglo'])
harris_precincts['%Anglo'] = pd.to_numeric(harris_precincts['%Anglo'])
harris_precincts['%Asian'] = pd.to_numeric(harris_precincts['%Asian'])
harris_precincts['%Black'] = pd.to_numeric(harris_precincts['%Black'])
harris_precincts['%Hispanic'] = pd.to_numeric(harris_precincts['%Hispanic'])
harris_precincts['%B+H'] = pd.to_numeric(harris_precincts['%B+H'])
harris_precincts = harris_precincts[harris_precincts['%Non-Anglo'] > 60.0]

Precincts      object
Population     object
Total          object
Anglo          object
Non-Anglo      object
Asian          object
Black          object
Hisp           object
B+H            object
%Anglo         object
%Non-Anglo    float64
%Asian         object
%Black         object
%Hispanic      object
%B+H           object
dtype: object

C:\Users\data30nana\AppData\Local\Temp\ipykernel_11776\3932089323.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  harris_precincts['%Non-Anglo'] = pd.to_numeric(harris_precincts['%Non-Anglo'])
C:\Users\data30nana\AppData\Local\Temp\ipykernel_11776\3932089323.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  harris_precincts['%Anglo'] = pd.to_numeric(harris_precincts['%Anglo'])
C:\Users\data30nana\AppData\Local\Temp\ipykernel_11776\3932089323.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  harris_precincts['%Asian'] = pd.to_numeric(harris_precincts['%Asian'])
C:\Users\data30nana\AppData\Local\Temp\ipykernel_11776\3932089323.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  harris_precincts['%Black'] = pd.to_numeric(harris_precincts['%Black'])
C:\Users\data30nana\AppData\Local\Temp\ipykernel_11776\3932089323.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  harris_precincts['%Hispanic'] = pd.to_numeric(harris_precincts['%Hispanic'])
C:\Users\data30nana\AppData\Local\Temp\ipykernel_11776\3932089323.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  harris_precincts['%B+H'] = pd.to_numeric(harris_precincts['%B+H'])

In [91]:
harris_precincts.dtypes

Precincts      object
Population     object
Total          object
Anglo          object
Non-Anglo      object
Asian          object
Black          object
Hisp           object
B+H            object
%Anglo        float64
%Non-Anglo    float64
%Asian        float64
%Black        float64
%Hispanic     float64
%B+H          float64
dtype: object

In [92]:
harris_precincts

,Precincts,Population,Total,Anglo,Non-Anglo,Asian,Black,Hisp,B+H,%Anglo,%Non-Anglo,%Asian,%Black,%Hispanic,%B+H
0,Harris,Total:,"4,731,145","1,309,593","3,421,552","392,435","981,484","2,034,709","2,967,268",27.7,72.3,8.3,20.7,43.0,62.7
1,,VAP:,"3,519,584","1,075,663","2,443,921","302,348","712,166","1,405,353","2,091,400",30.6,69.4,8.6,20.2,39.9,59.4
12,6,Total:,"8,814","2,294","6,520",292,"2,862","3,378","6,070",26.0,74.0,3.3,32.5,38.3,68.9
13,,VAP:,"6,379","1,945","4,434",224,"1,916","2,277","4,095",30.5,69.5,3.5,30.0,35.7,64.2
14,7,Total:,"1,294",32,"1,262",9,754,507,"1,253",2.5,97.5,0.7,58.3,39.2,96.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2299,,VAP:,119,15,104,2,6,98,104,12.6,87.4,1.7,5.0,82.4,87.4
2300,1148,Total:,"2,720",163,"2,557",273,578,"1,727","2,281",6.0,94.0,10.0,21.3,63.5,83.9
2301,,VAP:,"1,970",139,"1,831",236,409,"1,198","1,593",7.1,92.9,12.0,20.8,60.8,80.9
2302,1149,Total:,"5,720","2,099","3,621",411,"1,573","1,653","3,127",36.7,63.3,7.2,27.5,28.9,54.7
2303,,VAP:,"3,945","1,529","2,416",285,"1,080","1,016","2,063",38.8,61.2,7.2,27.4,25.8,52.3

In [93]:
harris_precincts = harris_precincts[harris_precincts['%Asian'] <= 12.0]

In [94]:
harris_precincts = harris_precincts[harris_precincts['%Hispanic'] >= 30.0]

In [95]:
harris_precincts = harris_precincts[harris_precincts['%B+H'] >= 60.0]

In [96]:
harris_precincts.shape

(926, 15)

In [97]:
harris_precincts

,Precincts,Population,Total,Anglo,Non-Anglo,Asian,Black,Hisp,B+H,%Anglo,%Non-Anglo,%Asian,%Black,%Hispanic,%B+H
0,Harris,Total:,"4,731,145","1,309,593","3,421,552","392,435","981,484","2,034,709","2,967,268",27.7,72.3,8.3,20.7,43.0,62.7
12,6,Total:,"8,814","2,294","6,520",292,"2,862","3,378","6,070",26.0,74.0,3.3,32.5,38.3,68.9
13,,VAP:,"6,379","1,945","4,434",224,"1,916","2,277","4,095",30.5,69.5,3.5,30.0,35.7,64.2
14,7,Total:,"1,294",32,"1,262",9,754,507,"1,253",2.5,97.5,0.7,58.3,39.2,96.8
15,,VAP:,987,27,960,9,627,328,952,2.7,97.3,0.9,63.5,33.2,96.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2283,,VAP:,"4,987",358,"4,629",158,"1,774","2,716","4,456",7.2,92.8,3.2,35.6,54.5,89.4
2298,1147,Total:,197,17,180,3,15,168,177,8.6,91.4,1.5,7.6,85.3,89.8
2299,,VAP:,119,15,104,2,6,98,104,12.6,87.4,1.7,5.0,82.4,87.4
2300,1148,Total:,"2,720",163,"2,557",273,578,"1,727","2,281",6.0,94.0,10.0,21.3,63.5,83.9
2301,,VAP:,"1,970",139,"1,831",236,409,"1,198","1,593",7.1,92.9,12.0,20.8,60.8,80.9

In [99]:
harris_precincts = harris_precincts.reset_index()
harris_precincts

,level_0,index,Precincts,Population,Total,Anglo,Non-Anglo,Asian,Black,Hisp,B+H,%Anglo,%Non-Anglo,%Asian,%Black,%Hispanic,%B+H
0,0,0,Harris,Total:,"4,731,145","1,309,593","3,421,552","392,435","981,484","2,034,709","2,967,268",27.7,72.3,8.3,20.7,43.0,62.7
1,1,12,6,Total:,"8,814","2,294","6,520",292,"2,862","3,378","6,070",26.0,74.0,3.3,32.5,38.3,68.9
2,2,13,,VAP:,"6,379","1,945","4,434",224,"1,916","2,277","4,095",30.5,69.5,3.5,30.0,35.7,64.2
3,3,14,7,Total:,"1,294",32,"1,262",9,754,507,"1,253",2.5,97.5,0.7,58.3,39.2,96.8
4,4,15,,VAP:,987,27,960,9,627,328,952,2.7,97.3,0.9,63.5,33.2,96.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921,921,2283,,VAP:,"4,987",358,"4,629",158,"1,774","2,716","4,456",7.2,92.8,3.2,35.6,54.5,89.4
922,922,2298,1147,Total:,197,17,180,3,15,168,177,8.6,91.4,1.5,7.6,85.3,89.8
923,923,2299,,VAP:,119,15,104,2,6,98,104,12.6,87.4,1.7,5.0,82.4,87.4
924,924,2300,1148,Total:,"2,720",163,"2,557",273,578,"1,727","2,281",6.0,94.0,10.0,21.3,63.5,83.9
925,925,2301,,VAP:,"1,970",139,"1,831",236,409,"1,198","1,593",7.1,92.9,12.0,20.8,60.8,80.9

In [101]:
harris_precincts.drop(['level_0', 'index'], axis=1, inplace=True)

In [102]:
harris_precincts

,Precincts,Population,Total,Anglo,Non-Anglo,Asian,Black,Hisp,B+H,%Anglo,%Non-Anglo,%Asian,%Black,%Hispanic,%B+H
0,Harris,Total:,"4,731,145","1,309,593","3,421,552","392,435","981,484","2,034,709","2,967,268",27.7,72.3,8.3,20.7,43.0,62.7
1,6,Total:,"8,814","2,294","6,520",292,"2,862","3,378","6,070",26.0,74.0,3.3,32.5,38.3,68.9
2,,VAP:,"6,379","1,945","4,434",224,"1,916","2,277","4,095",30.5,69.5,3.5,30.0,35.7,64.2
3,7,Total:,"1,294",32,"1,262",9,754,507,"1,253",2.5,97.5,0.7,58.3,39.2,96.8
4,,VAP:,987,27,960,9,627,328,952,2.7,97.3,0.9,63.5,33.2,96.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921,,VAP:,"4,987",358,"4,629",158,"1,774","2,716","4,456",7.2,92.8,3.2,35.6,54.5,89.4
922,1147,Total:,197,17,180,3,15,168,177,8.6,91.4,1.5,7.6,85.3,89.8
923,,VAP:,119,15,104,2,6,98,104,12.6,87.4,1.7,5.0,82.4,87.4
924,1148,Total:,"2,720",163,"2,557",273,578,"1,727","2,281",6.0,94.0,10.0,21.3,63.5,83.9
925,,VAP:,"1,970",139,"1,831",236,409,"1,198","1,593",7.1,92.9,12.0,20.8,60.8,80.9

In [ ]:
# All remaining precincts are comparable to the target precincts. So, 15 will be selected randomly to compare to the original 15 targeted by BakerRipley.